# -*- coding: utf-8 -*-
"""Project COVID-CT Scans (Part 1)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NN310JpPp3UBzZ4M2X3fUGIW7Ppu5khn

# Splitting the Data into train, validation and test sets
"""

!pip install split-folders

# import split-folders
import splitfolders

splitfolders.ratio(input = "/content/drive/MyDrive/Project COVID-CT/Data",
                   output = "/content/drive/MyDrive/Project COVID-CT/Output",
                   seed = 2021,
                   ratio = (0.7, 0.15, 0.15))